openapi: 3.0.0

info:
  title: Contact Manager API
  version: 1.0.0

paths:
  /api/auth/register.php:
    post:
      summary: Register a new user
      responses:
        "201":
          description: User created successfully

  /api/auth/login.php:
    post:
      summary: Login user
      responses:
        "200":
          description: Login successful

  /api/auth/logout.php:
    post:
      summary: Logout user
      responses:
        "200":
          description: Logout successful

  /api/auth/session.php:
    get:
      summary: Check current user session
      responses:
        "200":
          description: User is logged in
        "401":
          description: User is not logged in
